### ISSUE TITLE
Post about upcoming TLS releases

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#320]
Issue to track a short series of posts about the upcoming TLS support in MirageOS. These are not in any particular order and content can probably be folded into a smaller number of posts.

All posts are intended for publication on ~~openmirage.org~~ **https://mirage.io** :)

- [x] Fri 26 Jun - Mirage release blog post (changes, features) by @samoht and @amirmc (include couple of short paragraphs on TLS Unix Tools -- docs page in #324). -- see also #345 

- [x] Fri 26 Jun - Security advisory process: i.e. who to get in touch with in order to report things.  This should be a v short page that highlights our process (essentially, send details to an email address).  This needs to be available at the same time we do the release post. @amirmc (and @avsm to set up the email address). -- see also #345 

- [x] Mon 29 Jun -  Bitcoin Pinata status/wrap-up post (already drafted in #322, @amirmc to review)

- [x] Tue 7 Jul - From certificate to secure site with `mirage seal` (aka roll your own pinata) by @yomimono (#335)

- [x] Thu 9 Jul - "Organised chaos: managing Entropy" by @pqwy

on hold for now:
- Testing and protocol compliance by @hannesm + @pqwy
- formal news release by @amirmc and LF

**Comment by amirmc** [comment]
@hannesm @pqwy @samoht @avsm please comment.  These posts would be scheduled for the last week of May.

**Comment by avsm** [comment]
Looks good -- one on testing and protocol compliance would be good to describe the trace checker (perhaps instead of TLS libs).

**Comment by hannesm** [comment]
one on TLS unix tools -- tlstunnel, jackline, s_client (not yet there) might be worth doing (read as I'm volunteering)
numbers in the pinata draft are subject to change (now that pinata run for another month ;)

**Comment by avsm** [comment]
Ah yes good point -- perhaps the TLS Unix tools could be a "different ways to deploy the stack and use it in your own apps"

**Comment by amirmc** [comment]
Edited the list.
- Swapped out TLS libs for TLS unix tools (which is way more interesting).
- Added Testing and protocol compliance
- Added speculative names for each piece of content

**Comment by hannesm** [comment]
updated list with names...

**Comment by hannesm** [comment]
update from talking with amir: 3 posts, monday, wednesday, friday:
pinata recap
tools (seal + unix tools)
entropy

then following monday press release (and mirage-2.5 release announcement) including usenix paper preprint.

**Comment by amirmc** [comment]
Thx for the reminder. I updated the top comment.

**Comment by hannesm** [comment]
I updated pinata numbers and PR #322

**Comment by amirmc** [comment]
Added a note about having a lightweight security process.

**Comment by hannesm** [comment]
I think https://github.com/mirage/mirage/issues/406 is blocking this (we should fix it before a release)...
on a second thought, tools etc. should go into wiki (as #324 does)... so, what about only pinata (wed) and entropy (fri), then press + paper preprint on mon?

**Comment by amirmc** [comment]
Yes, 406 definitely needs to be fixed before publicising.  We had a buffer of a week so we can use that now (the news release also still needs work).

I’ll push back the dates so that we can get the issues fixed over the coming week.  That’s still before the next public talk (Anil at QCon NYC).

I agree that TLS tools belong in the wiki but it’s very useful to have a pointer to them from the blog (cf. the short Pinata post I added).  The majority of the ‘meat’ (i.e. content) can go in the wiki but I think it’s important to have something in the blog feed.  It allows us the opportunity to provide much more context and narrative around the relevance, whereas the wiki should act as just the ‘what’ and ‘how to’ — I hope that makes sense.

We should also do something similar for the security advisory process (even though it’ll be lightweight).

I’ve adjusted the issue above with a new set of content/dates.  

AC

**Comment by amirmc** [comment]
@samoht could you send me a couple of sentences on Mirage Seal for the news release?

**Comment by amirmc** [comment]
Hi folks, Pls see my comment on the releases at https://github.com/mirage/mirage/issues/409#issuecomment-108438612

**Comment by amirmc** [comment]
After a chat w @samoht today, I've updated the dates/posts in the issue.

**Comment by hannesm** [comment]
great. regarding security: did anyone approach xenproject to have them setup a private mailing list for mirage to act as security contact?
unrelated: in the news release (or somewhere else?) there should be sth about logjam and ocaml-tls

**Comment by amirmc** [comment]
Re: Security mailing list.  I think this might be one we should set up ourselves. Xen Project has it’s own list that’s distinct to the other mailing lists.

Re: Logjam and OCaml-TLS. Yup, we should add info about this but I need to chat with you first.

**Comment by amirmc** [comment]
Hi folks,  Just a note that I have a call with LF this afternoon. We're discussing the release (inc timing) so I'm adjusting the schedule above (it only affects the first two posts for now).

We may need to adjust again.  I'll comment here either way.

**Comment by amirmc** [comment]
> We may need to adjust again. I'll comment here either way.

I need to try rewriting this to get the message across more clearly.  I can discuss this on this week's dev call but for the time-being I won't be merging any posts just yet.

**Comment by samoht** [comment]
@amirmc any update on this? Would it be possible to update the dates of the blog post release to match what is planned? Thanks!

**Comment by amirmc** [comment]
I'd like @avsm to catchup and comment as to where things stand.

**Comment by amirmc** [comment]
I updated the schedule with the latest thoughts. The order is slightly different as we'd lead with the release and the changes this introduced (important to get that out there quickly).  It would be good to know if there will be any further releases that might affect any instructions.

**Comment by hannesm** [comment]
mirage-seal instructions currently depend on `openssl`, but soon [tm] we should have another nocrypto/tls/x.509 release (strictly needed is only X.509 + naming branch, but this involves changes to TLS, and Nocrypto API changed as well) which enables https://github.com/yomimono/ocaml-certify (and unbreaks https://github.com/hannesm/tlsclient).

@pqwy any idea when nocrypto release will be ready and when you'll find some time to look through https://github.com/mirleft/ocaml-x509/pull/54 ?

**Comment by samoht** [comment]
I'm still updating `mirage-www` to deploy both https://mirage.io and http://openmirage.org. The current state is here: https://github.com/mirage/mirage-www/pull/317 I need to check that the redirection works fine and to sort out how to mount a fat image on the deployment server.

**Comment by amirmc** [comment]
Hi folks,

Just a quick note to clarify what's happening.

- We're continuing with blog posts about the recent TLS integration work (schedule above).
- We'll time the first post with/after the switch to using https://mirage.io as the canonical URL (old URLs will redirect).  It makes sense to do this together. @samoht, is it ok to schedule this switch for tomorrow?
- I'll send a note to the main list today to encourage people to try things out now (will also point to the breaking changes page).

Amir

**Comment by amirmc** [comment]
First set of content is now in #345.

**Comment by amirmc** [comment]
Hi folks, I'll be merging the Piñata review post this afternoon.

**Comment by amirmc** [comment]
Piñata post is now live at https://mirage.io/blog/bitcoin-pinata-results

**Comment by amirmc** [comment]
@pqwy How is the Entropy post coming along? ;)

**Comment by pqwy** [comment]
@amirmc *Slowly* :smile: But I hope to have something to show tomorrow.

**Comment by amirmc** [comment]
Hey @pqwy, anything to review? Would be great to have something to look over by Weds. [insert emoji that signifies 'hopeful']

**Comment by pqwy** [comment]
@amirmc 

Raw text in #361. Needs cleanup and review, not sure if It can be ready by tomorrow, but Thu surely.

Apologies for being glacially slow.

**Comment by amirmc** [comment]
Last post in this list is now live.
